### ISSUE TITLE
Missing Command-line Arguments "--logfolder [path]"

### ISSUE THREAD

**Issue by Stolzenberg** [eisengrind/docker-altv-server#22]
Hey,

would be cool if we could use the `--logfolder [path]` command-line argument as environment variable.

**Comment by pixlcrashr** [comment]
Thanks for your inquiry!

You already can use this option by providing the environment variable `ALTV_SERVER_LOG_PATH`.
For reference, see https://github.com/eisengrind/docker-altv-server/blob/master/.docker/scripts/entrypoint.sh

**Comment by Stolzenberg** [comment]
Thanks for the fast reply.

Oh I thought, --logfile and --logfolder have [different behaviours](https://docs.altv.mp/articles/commandlineargs.html). With the current implementation we only can have one logfile, that is getting cleaned after server restart. With --logfolder we can have a folder with files for each server session.

**Comment by pixlcrashr** [comment]
> Oh I thought, --logfile and --logfolder have [different behaviours](https://docs.altv.mp/articles/commandlineargs.html). With the current implementation w

Oh, I see. I didn't read "logfile". Currently, there is no option for specifying the logfile name indeed.
Well, good that you bring up that point. I'll add it in the next few days.

**Comment by Stolzenberg** [comment]
Maybe I can create a PR later after work. 

I'm not that familiar with editing and setting up Dockerfiles, but adding another environment variable and adding it as a command line argument sounds pretty doable cause of your entrypoint.sh setup.

**Comment by pixlcrashr** [comment]
@Stolzenberg `--logfolder path` support is added by using the `ALTV_SERVER_LOG_FOLDER` env var: 5da2cfd9d96945c0cd4651c48e7784ced49876af

FYI: You also could add the parameter at the end of the docker container start, e.g.:
```
docker run -it eisengrind/altv-server --logfolder xyz
```
The Docker image does support additional parameters which are not covered by any env vars.

**Comment by pixlcrashr** [comment]
Image is published if https://github.com/eisengrind/docker-altv-server/actions/runs/2719693308 is ready

**Comment by pixlcrashr** [comment]
@Stolzenberg Is everything working alright?

**Comment by Stolzenberg** [comment]
I'm testing it right now.

**Comment by Stolzenberg** [comment]
Hmh I'm not sure if I misunderstand something in the setup or it does not work for me.

It should create the log files in the specified folder according to server session, right?

I added to my docker-compose.yml the environment variable:
`ALTV_SERVER_LOG_FOLDER: "logs"`

And I created a new folder names "logs" in my server directory. 
![1Shx67K](https://user-images.githubusercontent.com/14137226/180655026-38cb4a9a-faa1-4705-b285-67ebbe6fca41.png)

But the logs directory is empty.

**Comment by pixlcrashr** [comment]
@Stolzenberg It was my bad. I fixed a typo that caused this in the last commit.
Wait until https://github.com/eisengrind/docker-altv-server/runs/7488912740?check_suite_focus=true is ready.

**Comment by Stolzenberg** [comment]
Does it work for you?

Because I still do not get any log files created.

**Comment by pixlcrashr** [comment]
@Stolzenberg First things first: The `--logfolder` CLI param does not exist (anymore?).
You can easily check this by downloading the latest release or development version of the alt:V server and type `altv-server.exe --help` to show the available CLI params. `--logfolder` is not listed - the documentation seems to be a bit outdated, though.

Therefore, I'll close this issue.

---

Anyway - why would you save log files within a container when you have an STDOUT (= `docker logs -f <container name>`), which essentially is the console's output.
One would rather use some monitoring system to make use of STDOUT logs.

**Comment by pixlcrashr** [comment]
FYI: I therefore removed the `ALTV_SERVER_LOG_FOLDER` env var.
